#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = [
#   "polars",
#   "seaborn",
#   "matplotlib"
# ]
# ///


import os
from pathlib import Path
import polars as pl
import seaborn as sns
import matplotlib.pyplot as plt
import argparse

if 'VIRTUAL_ENV' not in os.environ:
    exit("Run this script using `uv` or from a venv to avoid polluting your system.")

print("Working directory is:", os.getcwd())

parser = argparse.ArgumentParser(
    description="Plot CPU and RAM usage file generated by `tu`.")

parser.add_argument(
    "-f",
    "--file",
    action="store_true",
    help="Locations of data file",
    default="task_usage.csv"
)

parser.add_argument(
    "-o",
    "--output",
    action="store_true",
    help="PNG output file location",
    default="plot.png"
)

args = parser.parse_args()

data_dir = Path(args.file)

data = pl.read_csv(data_dir)
print(data)

melted = data.unpivot(on=["cpu_percent","ram_percent"], index="elapsed_seconds")
print(melted)

g = sns.FacetGrid(melted, row="variable", sharey=False, aspect=2)
g.map(sns.lineplot, "elapsed_seconds", "value")
plt.savefig(args.output)